version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'postgres15'
    ports:
      - 15432:5432
    environment:
      - 'POSTGRES_USER=pguser'
      - 'POSTGRES_PASSWORD=pgpass'
      - 'POSTGRES_DB=product_db'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'